title: My Webpage
author: acharyariku
email: acharyariku@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello, Welcome to Anshuman's Website

# social links
twitter_username: acharyariku # DO NOT include the @ character, or else the build will fail!
github_username:  acharyariku # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
